### ISSUE TITLE
provider is not defined before the end of the __init__

### ISSUE THREAD

**Issue by guiguem** [project8/dragonfly#105]
Maybe this is a known feature, but using a self.provider.cmd inside the init does not work: provider is a None.
One has to wait until the end of the __init__ to get the provider set to the right value.
A special case where one would like a function using provider to be executed at the end of the __init__ is the pinger:
```
class Pinger(Endpoint):
    '''
    Ping on a regular basis a list of service.
    It sends a request to target.ping, if a response is not given within the timeout,
    it reports a logger.critical, which sends a alert to status_message.critical.<service_name>
    via the AMQPHandler.
    '''
    def __init__(self,
                 broker=None,
                 ping_interval = 60,
                 services_to_ping = [],
                 ping_timeout = 10,
                 *args, **kwargs):

        Endpoint.__init__(self,**kwargs)

        self.ping_interval = ping_interval
        self.services_to_ping = services_to_ping
        self.ping_timeout = ping_timeout

        # sleep before starting pinging the services
        sleep(self.ping_interval)

        # start the ping
        # logger.info("Starting ping")
        # self.start_ping()

    def start_ping(self):
        while (True):
            message = ""
            for item in self.services_to_ping:
                logger.info("pinging {}".format(item))
                try:
                    result = self.provider.cmd(target=str(item), method_name="ping", value=[], timeout=self.ping_interval)
                    if result:
                        logger.info("{} is responding".format(item))
                except Exception as err:
                    logger.info(err)
                    message = message + "{}\n".format(item)
            if message != "":
                logger.critical("The following services are not responding:\n{}".format(message))
            sleep(self.ping_interval)
```
Is there a hack for that?

**Comment by wcpettus** [comment]
I don't think this is a bug -
In the case of pinger, there is a top level `pinger_service` (a Spimescape) and a lower level `pinger` (a Pinger).  The top-level pinger_service has access to the service methods and can communicate with the broker, the lower-level pinger can only communicate through its top level Service (Spimescape inherits from Service).

The way we accomplish this occurs in `open_spimescape_portal.py` - you create the top level, then you create the lower-level, and after the lower-level is initialized, you run the `Spimescape.add_endpoint` method which allows it to access `self.provider.`

As for a hack, isn't this what `setup_calls` allows?  The muxer has a `configure_scan` method which is accessed this way and is largely analogous (although it uses self.send, not self.provider)

**Comment by laroque** [comment]
Walter is correct, this is not a bug. The `__init__` functions are similar to constructors and ensure that the state of the class if fully configured when you create an instance, but they cannot be responsible for the state of other classes because it depends on when you instantiate them (you have to create both a provider and an endpoint before you can tell them that they are related). This is the same as a `Spime` which logs some sensor, at the end of its `__init__` it is ready to talk to hardware, but the value logging doesn't actually start until a setup call prompts the command to start logging.

The pinger service should be configured (in the yaml file) with a setup_call which is an OP_CMD to `start_ping`. The muxer's config is presumably a good example.
