### ISSUE TITLE
Stop the ping of a service

### ISSUE THREAD

**Issue by guiguem** [project8/dragonfly#120]
We could have a dictionary of the active services to be pinged in top of the initial list from the config file.
We could activate them and disabling them without touching the config file and get this dictionary in a nice formatted way via a command.
A firefly page controlling/reading this would be vey useful too.

**Comment by wcpettus** [comment]
As of v1.9.0, it is possible to silence a pinger for a 24 hour period via:
`dragonfly cmd pinger.silence_ping service_name timestamp`

I won't claim that it has the most inspired implementation, but this exists.

**Comment by guiguem** [comment]
there are no method to unmute services without restarting the pinger or waiting until the timestamp.
This issue is not a missing item, but an enhancement.
Having a unified dictionary that states the status instead of two dictionaries will make easier an integration to firefly I think

**Comment by wcpettus** [comment]
The `silence_ping` command overwrites any previous silencer, so issuing a timestamp in the past will unmute the pinger for that service.

Define what precisely you want to see on firefly from an operations perspective (do you want memory of whether it missed its last ping?), and it should be possible to implement.  Unless we decide to punt and switch to heartbeats.

**Comment by guiguem** [comment]
![img_1265](https://user-images.githubusercontent.com/16764756/31139501-a68d99c0-a826-11e7-8702-6f901292c1a3.JPG)

**Comment by wcpettus** [comment]
Resolved as of release v1.9.2

There is now a method `dragonfly get pinger.ping_status --pretty-print` which will return as value_raw a dict of every service that is getting pinged, a status, and the timestamp of last ping (or timestamp when it will be active again because the silence expires), if no valid ping has returned the timestamp will return None.  value_cal is a formatted string for pretty-print
