### ISSUE TITLE
DAQ standards for timed runs

### ISSUE THREAD

**Issue by wcpettus** [project8/dragonfly#135]
What is the proper way to implement a timed run and ensure the DAQ stops properly?

- For the RSA, a run is defined by turning on the trigger and saving data, timing of runs is handled entirely within dragonfly, so we need
```python
self._stop_handle = self.service._connection.add_timeout(self._run_time, self.end_run)
```
- For the ROACH/psyllid, it is intelligent and knows how long a run you want, so the timeout with callback to end the run shouldn't be necessary.
  - We can still implement it as in the RSA to be parallel.
  - psyllid could have a callback when it finishes to trigger the `end_run` DAQ method (get the snapshot, etc.)

Currently the ROACH DAQ provider does implement the timeout, but isn't uniform in cleaning up for aborted runs.  We should define the preferred behavior and clean the code accordingly.

**Comment by nsoblath** [comment]
Psyllid sends out an alert, I believe, when a run is completed.  This could potentially be used to trigger the `end_run` method call.

**Comment by wcpettus** [comment]
It's dangerous and/or irritating to keep redundant time.  The best case scenario is:
- We add dead time (because the dragonfly DAQ consistently "ends" the run after psyllid is idle)
- We shorten runs (because the dragonfly DAQ consistently "ends" the run before psyllid)

The worst case scenario is:
- sometimes dragonfly is faster, sometimes slower, and livetime calculations are a pain

If psyllid is already sending an alert message, the DAQ can be a gogol to catch that and trigger its wrap-up.  What's the queue name?

**Comment by nsoblath** [comment]
I chose to make psyllid responsible for the timing of its runs because it would result in runs close to the right duration, and it could calculate its own livetime (which it currently doesn't yet do).

Looking at the Psyllid code, I see that I spoke slightly too soon about a dripline alert being sent for finished runs.  At one point a while back we were considering a couple of related additions: sending DL alerts for the DAQ system to know what's going on, and posting Slack messages for people to know what's going on.  The latter was implemented, but the former was not.  So currently we post Slack messages but do not send out anything else.

That said, it would be relatively easy to add sending alerts when runs are completed (or for any other events useful for synchronizing the components of the DAQ system).

**Comment by wcpettus** [comment]
Does it make more sense to do this as a request message or alert?  Psyllid would never be ending a run without a dragonfly DAQ controlling it, true?

**Comment by nsoblath** [comment]
Psyllid can be run without dragonfly, even if in the production system it would not be.  I suppose we could put in some logic to only send a request if it was started with a dripline request, but that would be significantly more complicated.

**Comment by wcpettus** [comment]
For now, dragonfly needs to cleanup its own timeouts.  After https://github.com/project8/psyllid/issues/49 we can remove timeouts from the dragonfly code.
