### ISSUE TITLE
Update endpoint list in insert status report

### ISSUE THREAD

**Issue by martinfertl** [project8/dragonfly#156]
There recently was an issue with the T2/Kr gas handling system that was not timely recognized by the operator of the instrument. The automatic shutoff valve SOV2 on the gas system was closed and stopped the gas flow into CRES cell. 

I request an update of the list of endpoints that is returned by
`dragonfly get insert_status -b myrna.p8 --timeout 20 --pretty-print`
to include the status_SOV1 and status_SOV2 endpoints.

This should allow the regular instrument operator to at least see the shut off valve status.

**Comment by laroque** [comment]
This is not a dragonfly issues, it is a configurable parameter of the insert_status endpoint (configured int he hardware repo).

Furthermore, it is not possible with the system as designed. It was an explicit design requirement that T2 controls be restricted and only accessible to the T2 operators group, adding this item to the insert_status endpoint is incompatible with that requirement.

We should have a higher-level conversation about our requirements and procedures. I suspect that for the overwhelming majority of cases, it would be better to have an insert status summary page on firefly, which displays the most recently logged state of everything (including how old those states are so we know if the values are stale). This would pull values from the database rather than actively talking to instruments and be compatible with things as designed. There may be other solutions which others prefer based on other requirements I'm not thinking of at the moment.

**Comment by guiguem** [comment]
I dont think an operator can do that, can s/he? I thought an operator cannot communicate with the Dorian broker where these endpoints are "registered" (sorry Ben for the inappropriate use of words...).
However an endpoint t2_gs_status could be created on the Dorian side for t2 operators which will be doing this job for the operator.
The gas system is a complex systen and just asking the operator to check the status of the system with one or two endpoints is not enough as it should be the job of the t2 operator.

**Comment by laroque** [comment]
Mathieu, a normal operator cannot do anything with the T2 zone, including get of whatever endpoints. However, both the T2 zone and the normal lab zone log values to the same database, which is read by the website. So we could make a firefly page on the normal Claude location which displays T2 information (it would not be able to do any of the interactive bits like changing valves or talking to the RGA, or issue a multi-get request). it would also be easy to make a multi-get on the T2 side that a T2 operator could use (via dragonfly command on dorian, or the T2 firefly running on dorian) to retrieve those values.

I think that the above partially but not fully overlaps with what you were saying, hope it is clear.

**Comment by wcpettus** [comment]
Closing this as a will-not-fix
