### ISSUE TITLE
Safer run script control

### ISSUE THREAD

**Issue by martinfertl** [project8/dragonfly#159]
I request a safer run script control that is not based on:
"Press Return to continue". Return is just a to often by accident hit key on a keyboard.
It seems that a mistakenly hit return key, while the execution script is running, is taken as confirmation of the requested user confirmation that a certain change to the system has been made (e. g.) setting up a pressure. See e.g. the screenshot here https://maxwell.npl.washington.edu/elog/project8/Project+8/2421. Between 18:42 and 18:46 i must have hit the return key. It seems that this caused the execution script to run over he operator requested change of the background pressure at 19:20 to immediately start the next daq run, without waiting.

I suggest a more explicit confirmation of operator requested work by requiring to confirm with a less accidentally hit key, either "y" or typing "yes"....

**Comment by wcpettus** [comment]
If someone else gets a chance to do this.  Look here in run_scripting:
https://github.com/project8/dragonfly/blob/develop/dragonfly/subcommands/run_scripting.py#L366

It should be a simple python fix to add logic to check the response, if it starts with a "y" to accept it, and otherwise re-post for raw_input (use a while loop?).  Can also force a string.lower() before checking to be case insensitive.

**Comment by wcpettus** [comment]
Resolved by Elise in v1.13.4.
