### ISSUE TITLE
Include threshold re-set in prepare_daq_system of ROACH1ChAcquisitionInterface

### ISSUE THREAD

**Issue by les67** [project8/dragonfly#171]
So far only the central frequency is 

> logger.info('Setting Psyllid central frequency identical to ROACH2 central frequency')
freqs = self._get_roach_central_freqs()
self.central_frequency = freqs[self.channel_id]

We need to do the same for the threshold property. This is helpful when getting the `Threshold mismatch` error from the psyllid interface and wanting to reset the properties of the daq so that roach and psyllid match up. So far this has been done manually with `dragonfly set r2_channel_b_threshold 14 -b myrna.p8` for roach channel b (for example)

**Comment by cclaessens** [comment]
This would be a good idea if we only use default trigger settings. But if at some point, we run in a configuration different from the default and prepare_day_system would set default trigger settings, it might go unnoticed that the trigger settings are no longer what they were planned to be.

For the moment I updated the wiki, so that it now tells the operator that running prepare_daq_system is not enough and that the trigger settings need to be reset too. But if we decide that trigger settings should only be set in config files instead of manually via dragonfly, this could definitely be combined to a single dragonfly command.

**Comment by wcpettus** [comment]
Statefullness in the ROACH/psyllid services is a larger problem, this particular component is will-not-fix, but we should keep having the conversation.
