### ISSUE TITLE
Endpoints which ensure a complex state could be useful

### ISSUE THREAD

**Issue by laroque** [project8/dragonfly#26]
We have MultiGet already, which allows a user to read a single endpoint and get the current value of many endpoints in reply. It would be useful to implement something similar for set, where a single abstract endpoint could be set in some way, and multiple endpoints get configured.

Use cases:
abstract_trap_coils.set('nominal') -> ensure power supply outputs are on, output relays are off
abstract_trap_coils.set('bathtub') -> ensure top and bottom coils have output relays on and polarities correct
full_system.set('dpph') -> enable dpph output, ensure data taking is off, ensure pin-switch is passing signals
full_system.set('data') -> ensure dpph is all off, ensure sweeper is off
full_system.set('panic') -> disable all current supplies etc.
...

This list could probably be made needlessly/arbitrarily long, but there are certainly cases where a human repeatedly does 3-8 sets and could easily forget one or not notice one failed if not paying attention.

**Comment by guiguem** [comment]
A MultiDo class has been implemented, this class posses endpoints which can be get or set. 
During this development an intermediate class MultiSet has been created (set several endpoints to a value): this class is not fully integrated but does its main job. 
Several features such as set_and_check have been implemented in the MultiDo. 
For safety reasons, some endpoints such as detector_status remain MultiGet (not MultiDo), since the detector status can only be get. 
In the same idea, the MultiSet class can be also used. Ideally, the MultiGet class should disappear and the MultiDo class/object should have a flag which will prevent from setting values (detector_status endpoint)/getting values (for multi endpoints which are just setting commands, such as the create_new_auto_mask).
