### ISSUE TITLE
SCPI Spime code cleanup

### ISSUE THREAD

**Issue by laroque** [project8/dragonfly#29]
There is code in many places (dripline and dragonfly) and things that should inherit don't seem to do so in all cases.

Solution:
1. Move all SCPI code out of dripline and into dragonfly, since that is where it goes
2. Pull all SCPI code into a single module (some is in the Prologix module, some is in SCPI, etc.)
3. FormatSCPISpime should support format/regex-parsing of responses from instruments when doing a get, as well as constructing complex commands
4. There should be a base class (possibly FormatSCPISpime, which may need to be renamed) which is most generic
5. There should then be a "SIMPLE" version of that for cases of a basic command which supports reading (add `?`) or writing (add `VALUE`); there should be either inherited classes or options in SIMPLE that only support read or only support write

**Comment by wcpettus** [comment]
Related issues are now associated.  Here is my general philosophy:
- The simplest Spime to use will be the SimpleSCPISpime, which is extended in a logical way to the SimpleSCPIGetSpime and SimpleSCPISetSpime.  They assume SCPI formatting and give useful results for most endpoints.
- The complicated Spime form is the FormatSpime.  Any functionality that any Spime might find useful should go here; currently that means unique get/set strings (get/set method disabled by setting to None), regex formatting that Mathieu already implemented to parse down TTi responses, set value dictionaries to map relays and other sets to specific formatting, and string case formatting.
- To expose an attribute of a provider as a spime, use ProviderAttributeSpime.  The two anticipated use cases are pid_loop.setpoint and rsa.trigger_status; the former provides logging for an internal variable, and the latter allows both user endpoint and internal rsa access to the same command (also we can protect it by disabling set).

Anything can (probably) be done with these forms, but for convenience there are a couple other Spime's:
- LockinSpime (and LockinGetSpime): lockin is IEEE 488 (not .2), so it doesn't follow normal conventions; this is essentially a "SimpleSpime" for the lockin (copied largely intact from my earlier implementation)
- MuxerGetSpime: takes care of formatting for the muxer (copied largely intact from Luis's original implementation); no set functionality for obvious reasons
- RelaySpime: simplifies implementation of all the relay endpoints and removes a lot of redundancy from the relay config (this is new)

Also of note, all the calibrations have been pulled together into a new file for order's sake.

Now to the checklist:
1 The code now is gone from dragonfly
1 The Spime implementations are all together in `spime_endpoints.py`
1 FormatSpime does this parsing (I didn't touch this, Mathieu solved this a while ago)
1 FormatSpime is the new incarnation of FormatSCPISpime
1 SimpleSCPISpime still exists and does this

Aside - Since most endpoints allow sending multiple commands together, I've rewritten the SimpleSCPISpime set to both set and check the same endpoint.  This ideally will obviate the need to "get_on_set", with the caveat that get goes through @calibrate and set does not, which results in different response formatting (values vs value_raw/value_cal).  This is really a different problem though and beyond the scope of this issue.

Testing ahead, but so far looking good.

**Comment by wcpettus** [comment]
resolved in release v1.3.3
