### ISSUE TITLE
Saving the temperature set for the PID loop into the metadata file

### ISSUE THREAD

**Issue by guiguem** [project8/dragonfly#43]
As it is now, the PID_loop_service does not provide endpoints for its parameters and we cannot save it as a metadata value.

**Comment by laroque** [comment]
This is in principle straight forward but involves changes to `dripline` rather than `dragonfly` (maybe both?).

In particular, the `dripline.Gogol` class needs to inherit from `dripline.Spimescape` rather than `dripline.Service` so that it will support responding to requests. There are some subtleties:

The way that `dripline.Service` uses `self._exchange` then needs to be made more general. In particular, ReplyMessages should be sent on the requests exchange, even if a Gogol is also bound to the alerts exchange.
It is important to be ensure that whatever changes are made to these base classes to allow the new inheritance don't change the default behavior for other derived classes (such as pure Spimescapes).

**Comment by guiguem** [comment]
As a patch for this issue before changing the inheritance of the pid_loop class, it seems possible for us to change the temperature_target (for example) using the `set pid_loop.target_temp` or something equivalent. this will change the target value inside the pid_loop: a nice function/endpoint to do this should be useful in that sense too...

**Comment by guiguem** [comment]
The PID now have endpoints (the target_value, the minimum current...) accessible via `dragonfly get/set`. 
However they are not logged into the slow control database yet and not added to the insert_status. 
I will add that very soon.

**Comment by laroque** [comment]
This is a breakdown of concepts. The attributes of the PID class (pid.target_value, etc.) are not endpoints, they are attributes of an endpoint (the pid class is an endpoint). An endpoint always has its own name and can receive request messages directly `dragonfly get <endpoint_name>` as opposed to `dragonfly get <endpoint_name>.<attribute>`. Logging is a property of a Spime, which is a subclass of Endpoint.

If these parameters (or any others) deserve to be logged, then they should be Spimes. We could trivially implement a class AttributeEndpoint(Spime), which can would get/set the value of the named attributes of its provider. That would then then keep the value stored in a single location (the class to which the value applies), but would give it full standing of a Spime, with the feature set that goes with that (including `log_on_set` for this particular case, the ability to log on set timed intervals or in the hybrid style, etc.).

**Comment by guiguem** [comment]
Ok thanks for the clarification. 
Maybe this feature of logging the target value somewhere is not of great interest.

**Comment by laroque** [comment]
Probably > 99% of the time, we are much more interested in the history of the actual temperature and not the parameters of the control logic (and for a tuning study, one can of course record them). I don't think it is a bad feature and it would be trivial to add (in fact, here it is if you want to add/test it):

```
class ProviderAttributeSpime(Spime):
    def __init__(self, attribute_name, **kwargs):
       Spime.__init__(self, **kwargs)
       self.attribute_name = attribute_name
    def on_get(self):
        return getattr(self.provider, self.attribute_name)
    def on_set(self, value):
        setattr(self.provider, self.attribute_name, value)
```

**Comment by wcpettus** [comment]
tied to resolution of #29

**Comment by wcpettus** [comment]
pid_loop service now declares a single endpoint `pid_setpoint` which can be accessed via dragonfly in the usual way `dragonfly get pid_setpoint -b myrna.p8` (as of release v1.3.3)

Feel free to rename as appropriate and add to whatever MultiGets you like.

So the issue isn't technically resolved since we don't get it, but the implementation is clear from here.
