### ISSUE TITLE
rsa_interface cleaning

### ISSUE THREAD

**Issue by guiguem** [project8/dragonfly#57]
Instead of sending directly commands such as 'TRIG:EVEN:INP:TYPE {};*OPC?', the rsa_interface should interact with the endpoints which are defined in the config file.
No new function should be required, only the use of interface.set/get.

**Comment by guiguem** [comment]
With the refactor/services (issue #55) release, the following changes needs to be done:
- mantis class should be removed or moved into a unused subfolder of dragonfly
- the command which make the insertion of the run name into the run database should be updated: Ben did something like that using the `self.service.cmd(daq_db_interface, 'do_insert')` method but this did not work since the daq_db_interface does not support this (kwargs missing...). We might have to change a bit the `do_insert` method to accept kwargs or improve the `provider.cmd` in dripline.
- replace every `send(IEEE_command)` with a `service.get/set`

**Comment by wcpettus** [comment]
@laroque any advice?
- if a provider uses self.provider.get/set for it's own endpoint, everything hangs from `dripline.core.service(525) -> request to send to <endpoint_name> is: {` until timeout since the provider is blocking itself
Is there a built-in method for a provider to get/set one of its own endpoints?

**Comment by laroque** [comment]
"ideal solution" (not actually useful): would be for a proper asynchronous implementation. This won't be possible until we move to python 3, should be the target for the dripline version used in phase 3 since I expect the task will be that timescale.

Re Mathieu's 2nd bullet: the run database interface, the run table has been working as it is for some time. We don't need to change the do_insert method signature. We may need to change service.cmd() so that we can create properly formatted request messages. For example, insert on the run table expects a run name but I don't see one there.

Re Walter's question: In what situation is the provider trying to talk to its own endpoint? Given the lack of the ideal async solution, a workaround will depend on the particular use case.

**Comment by wcpettus** [comment]
I've got Mathieu's bullet 2 solved, it's a bullet 3 issue.

In splitting the RSA into two services, most methods felt more natural going with the instrument.  If you look at the set_default_config method of the feature version of rsa_provider:
https://github.com/project8/dragonfly/blob/feature/refactor_cleaning/dragonfly/implementations/rsa_provider.py
Setting a default config requires setting a lot of endpoints.  They could be explicitly accomplished with self.send commands, but that's back to what Mathieu's issue was pushing against.

Alternatively that method could move back to the rsa_daq class, but they are really instrument interactions.

**Comment by laroque** [comment]
Okay, so here we've hardcoded a bunch of endpoint names into the rsa_provider, which it will try and "set" to get to a default configuration. That means that a config file is only valid if in addition to this provider, it also creates all of those endpoints, which is hugely violating the purpose of the config files. If you're going to make the assumption/requirement that those endpoints exist, you could just as easily do `self.endpoints['whatever_I_want_to_set'].on_set(whatever_value_I_want)`. The expectation is that you can create an instance of any class and it should work in a self contained way, if it needs to talk to something else then you need to be able to configure where that is done (you tell the DAQ coordination classes the name of the run_table endpoint for getting run_id values and for the daq that will be used).

The way I think we need to look at it, given the constraints in the core system as it exists, is that a service is either providing an interface to an object, or it is implementing logic, but you can't do both in the same service. So, for example, The RSA interface service can have a bunch of endpoints for those individual settings, then we create a new "RSA_multiset" service, which implements the convenience feature of "ensure default config" which does all of those sets (it could have many states, maybe one for taking data, one for in lab demos, one wider band noise floor measurements, whatever else we may want). **Or** we can say that ensuring the default configuration needs to be part of the RSA interface itself, as a method of the provider class, in which case the provider needs to know a set of commands to make that happen. A provider which talks to an instrument is the intermediary by which its endpoints may get to the hardware, it doesn't make sense for it to go through other endpoints to talk to its own instrument.

**Comment by wcpettus** [comment]
Towards a possible solution - the functionality exists to do this with a MultiDo with everything specified as a default_set option.  It's a little broken because you will be calling `set set_rsa_default_config 1` (or whatever you called your endpoint) with some dummy set value which you then completely ignore.  Or possibly with a slight expansion we can achieve the same effect for this (and any other DAQ which wants a safe default config) with more intuitive naming.

The original point of this issue, which I agree with, is that it is very strange behavior to define the same SCPI string twice - once in the config to make an endpoint and once in a function method (that's what it looks like if you check the code in develop, all these defaults are accomplished with self.send()).

**Comment by laroque** [comment]
I believe that a MultiDo (running in its own service) is the cleanest solution available, at least for now. What I was suggesting is that perhaps the endpoint should be named something like rsa_operation_state, perhaps that looks like this:

State == 0 ("interactive")
<do all the sets to get to a state where a user can look at electrons interactively, maybe demo to a funding agency rep walking through lab; no triggering or saving data, just updates to the display>

State == 1 ("take data")
<ensure all data taking defaults are set for the trigger and whatever else, this is the one we're disucssing here>

Presumably internally to the MultiDo, we can use the value of the set to compute the value we actually set for each endpoint. This would be the same as how if I want a multi-do to give me a 1 amp bathtub, it has to go set the polarity and enable/disable relays for all the trap coils, set voltage and current limits.


Mostly unrelated but concerning, I just noticed that there are hard tabs mixed into this file. Please convert all \t to an appropriate number of spaces. This is an easy find/replace and setting in whatever editors people are using.

**Comment by wcpettus** [comment]
If I'm interpreting your meaning correctly, this MultiDo could go in the already existing service which has all the other multiget/set/do behavior (https://github.com/project8/hardware/blob/master/software_config/dragonfly/Phase2/status_multigets.yaml)

I'm sure this has already been discussed or thought about - why does a single instrument MultiThing have to live in a separate config from its other endpoints?  Why don't we put the MultiDo for the rsa_defaults in the rsa.yaml and the MultiGet for lockin_settings in the lockin.yaml?

Thanks for the catch on the tabs, I hadn't been checking those and just copy/pasted over to the new file.

**Comment by laroque** [comment]
2nd point: A MultiDo for a single instrument can't go in the service for that instrument (or for the interface) because a service processes requests serially. If one endpoint in a service tries to talk to another endpoint in that service it will block. This is the same core behavior problem from above. There is an obvious and clean solution, which is to move dripline to python3 (requires dealing with api changes in pika 0.10 or whatever the current release is now), and then using the asyncio library (formerly tulip) which has become part of the standard library.

If the above were fixed, then it would be very sensible that a multiset for a particular instrument would live in the same service as the lower-level endpoints and the instrument provider itself.

As for putting it into status_multigets.yaml, I strongly dislike having  unrelated components be part of the same service for two reasons below. Also note that the only cost of having more services is that we have to manage running all of them. Supervisord should make this much easier so I don't see it as a problem.
1) Unrelated components shouldn't be tied together. If we discover a bug or want to test changes to one component, we shouldn't have to deal with interruptions in unrelated components. I thought that status_multigets was "related" in that it just has MultiGets for a few different states (everything, things that should be tags for the DAQ, etc.). If it has become a catch-all we should break it up.
2) The same serial processing of requests issue from above exists. If setting the RSA configuration takes tens of seconds, and if it is in the same service as full_experiment_status, then the latter is blocked while the former is going.

**Comment by wcpettus** [comment]
Update:
- The bulk of these offending methods have been removed, since the endpoints are all defined in the hardware config
  * the `set_default_config` has moved to the rsa_multido service
- The `start_run` and `end_run` method both contain self.send("IEEE strings") as these are complicated procedures to implement which operators should not be trying to break down and separate
- the `rsa_trigger_status` is doubly implemented, as this is under consideration to be protected so users do not set the endpoint
- the `create_new_auto_mask` convenience method is being re-implemented to ease implementation of the auto mask, which breaks this guideline

**Comment by wcpettus** [comment]
as of release v1.2.4, the `create_new_auto_mask` method is removed, only duality remaining is `rsa_trigger_status`

**Comment by wcpettus** [comment]
rsa_trigger_status resolution tied to #29

**Comment by wcpettus** [comment]
fixed in release v1.3.3
