### ISSUE TITLE
Exchange confusion

### ISSUE THREAD

**Issue by guiguem** [project8/dragonfly#58]
It seems that the requests coming from longmorn (which ask for a voltage of balvenie for example) are directed to both the alerts exchange and the requests exchange.
This can be monitored using the `dragonfly monitor -b myrna.p8 -e alerts` and `dragonfly monitor -b myrna.p8 -e requests`.
Since they are requests, they should only appear in the requests exchange

**Comment by guiguem** [comment]
Update: with the new power supply for the cell heater, longmorn (which was the instrument that triggered this issue) is no longer used. 
The problem might still remain but we can independently use the power supply without perturbations the experiment.

**Comment by wcpettus** [comment]
This should still be double checked for the lockin/wolfburn.

**Comment by wcpettus** [comment]
Communication with lockin doesn't go over alerts.  Lockin uses its own special endpoint format and not normal Spimes, so it isn't simple to test logging of its endpoints.

Since we can't reproduce and have moved away from prologix boxes wherever possible, this issue is closed without any plan to follow up and fix.
