### ISSUE TITLE
[Fixed] Gogol inheritance changes breaks slow_control_service

### ISSUE THREAD

**Issue by guiguem** [project8/dragonfly#62]
After having changed the Gogol into a Spimescape, the slow_control_service which is an object of SensorLogger could start but crashed when asked to save a endpoint in the database because no table were declared in the object.
SensorLogger inherits from Gogol and PostgreSQLInterface.
It turned out that the method 'add_endpoint' from PostgreSQLInterface which was used before this change when creating the SQLTable objects (id_map_table, numeric_table and string_table) was not used anymore; instead the 'add_endpoint' method belonging to Provider class was used.
This is due to the new Gogol inheritance from Spimescape.
The fix was to define a add_endpoint method in the SensorLogger which explicitly uses the PostgreSQLInterface 'add_endpoint' method.

A possible good practice would be to always clearly define methods in a class which inherited from 2 classes, in order to avoid unexpected bugs in the case of inheritance changes.

**Comment by laroque** [comment]
Oh yes, this is part of why I try to use layered inheritance instead of multiple inheritance through the code. In this case that doesn't really work since the SQL interface certainly should not be a service

The best practice when overriding a method in a derived class would be to explicitly consider and treat the parent implementation for each parent that implements the method. (That may or may not mean calling the parent method, depending on if one intends to replace behavior or extend it). If not calling the parent method, it is usually good to have a comment that explicitly states that we want to replace that behavior and haven't forgotten to call it. If the order doesn't matter, it is nice to take care of calls to parent classes at the start of the method, but since the order can matter it is not reasonable to demand this.

**Comment by guiguem** [comment]
Was fixed
