### ISSUE TITLE
RSAProvider.create_new_auto_mask error handling

### ISSUE THREAD

**Issue by les67** [project8/dragonfly#70]
A run script was tested (dry-run mode) which made a call to the method RSAProvider.create_new_auto_mask. The DriplineError raised within this method should've crashed the script while in dry-run testing but the error was seemingly ignored and the dry-run executed successfully. Made an explicit call to this method via the CLI with `dragonfly cmd rsa_interface.create_new_auto_mask trace="TRACE3'" xmargin="1E+6" ymargin="14"` and no error was reported nor any crash. The message sent with the raised exception in the method, "convenience method <create_new_auto_mask> not yet implemented", was only posted with a logger.info via dipline_agent upon receipt of the message.

Proper error handling is necessary here so that this method, if not working, crashes the operation when called.

**Comment by wcpettus** [comment]
The issue is that I used a `raise DriplineError` as my exception, because I wasn't inspired by the match with any other error and wanted it to be generic.  Looking at dripline endpoint and exceptions, this returns a recode of None, which is identical to the behavior if no exception was raised.  Using any other flavor of DriplineException yields the desired result.

@laroque, some advice?
- either the retcode of DriplineError (and maybe DriplineWarning? that doesn't seem to get flagged on return for the user) should be changed to get better behavior
- or if these are doing specific internal things that are important, a header note should be added to these exceptions that they shouldn't be carelessly implemented in dragonfly code

**Comment by guiguem** [comment]
The create_auto_mask method has been removed by Walter.
I updated the rsa wiki page to reflect this change.
The new way to create a mask is 
``` dragonfly set rsa_new_auto_mask 14 -b myrna.p8```

**Comment by les67** [comment]
With the method removed and a new command available, this issue is being closed.

**Comment by laroque** [comment]
Re: Walter's post above:

-  My first reaction is that we should either figure out that there is an existing exception that matches this cases, or we should create a new one that does so. Based on the fact that Luis quoted "convenience method <create_new_auto_mask> not yet implemented", I'd think that this should be a code 306 `DriplineMethodNotSupportedError`, but perhaps I'm not understanding the situation.
- I should add comments to the exception module, will do that (probably right after this post); they will look like the items below
- I'm open to discussing item 3 (the behavior of DriplineError) if you don't find the following compelling

1. `DriplineException` is an "abstract base class" (ie, it implements the result field feature of dripline exceptions, which allow ReplyMessages to be sent which have both a non-zero error code and also content in the payload). Additionally, it is a common base class for all dripline exceptions, so one can write a `try`/`except DriplineException` block and it should catch any exception raised by our code (but not those from libraries, which use their own or standard library exceptions). It is a base class for both `DriplineError` and `DriplineWarning` but is not intended to be used directly.
2. `DriplineWarning` is a baseclass for issuing warnings (return codes 0-99). It is the base class for any other, more specific, warnings we may want to add. My expectation was that this would be used more frequently in debugging situations, and that there wouldn't be too many specific cases where it is needed long term, so the catch-all seemed okay. It exists so that in a `try`/`except` block, the except clause can more easily match against Warnings and Errors independently and treat them differently.
3. `DriplineError` is the base class for errors. As above, it mostly exists so that a `try`/`except` block can easily deal with errors and warnings properly/independently. In a dripline interaction, the "century" of a return code is intended to give an indication of the sort of problem that has occurred. The multiples of 100 are intended as generic within some class of problem, with more specific errors in the intermediate values for specific cases we want to be able to identify and treat (ethernet provider connection situation being the perfect example here). Because there are already quite a number of them, and because error handling is often part of the desired implementation, my expectation was that we would always isolate the problem to the 100s level.

**Comment by laroque** [comment]
following up: I've added docstrings to the three classes discussed above describing the above. These changes are merged into develop.
