### ISSUE TITLE
DAQ-related services should support condition setting

### ISSUE THREAD

**Issue by laroque** [project8/dragonfly#71]
This depends on the corresponding dripline feature being implemented first. Every DAQ will need to implement a set_condition response for aborting data taking. This includes immediately stopping the DAQ (instrument service) and presumably some cleanup (whatever metadata steps are part of ending the run/cleanup).

This issue is a bit of a placeholder until the dripline dependency is taken care of. We need to discuss exactly what condition value(s) we want to support and exactly what the expected behavior(s) is(are).

**Comment by guiguem** [comment]
A first task is to define a list of desired action associated with a condition number: for example, 10 is stop taking data with all the DAQ system (aka in DAQRunInterface), 11 only the RSA, 12 only the ROACH...
There might be some optimal design of this that we should consider before implementing the set_condition on the relevant classes.

**Comment by guiguem** [comment]
Also, it will be great if a set_condition could be catch when executing a script, such that the script just stops.
Since that seems very difficult to implement (run_scripting is always executing a method when running), the run_scripting should be said to stop by the daq themselves.
When getting a set_condition, I would suggest that the DAQ should be set into a safe mode where the current data taking is stopped and no data taking can happen until someone has unset the instrument to safe mode (for example we could use a set_condition 0).
This safe mode state is saved inside the class object.
Such system will allow us then to shutdown the execution of scripts: every X seconds, run_Scripting checks if the DAQ is running.
Usually it gets a 0 or 1 depending on the status of the DAQ: this could be upgraded to something more verbose, such as "is_running", "is_not_running" and "safe_mode".
If the DAQ is in safe mode, the run_scripting will gracefully stop after sending an alert...

This implementation might be a bit more than what was envisioned initially, but it should be easy to implement.
@laroque @wcpettus could you comment on that? Does it sound reasonable? Do you see some possible other improvements?

**Comment by guiguem** [comment]
The main feature has been implemented, we will have to make the logger.critical of set condition more explicit (or remove them). 
We could add a dictionary in dripline.constants, with standardized message based on the number. 
I am going to close the issue.
