### ISSUE TITLE
SQL snapshot best practices

### ISSUE THREAD

**Issue by wcpettus** [project8/dragonfly#79]
This is intended as a discussion thread to resolve some of the outstanding issues with the SQL snapshot.

1. Where should the SQL snapshot service(s) run?
  - how many large messages are we transmitting between machines?
  - how much data are we sending via dripline (see issue https://github.com/project8/dripline/issues/168)
2. Should the SQL snapshot be taken as an alert or request?
1. How many SQL snapshot files should be written?
1. What data should be saved in the snapshot?
  - value_raw / value_cal / both?
  - which endpoints?
5. Should we be saving the start/stop time?

A little elaboration:
1. The two proposed models are having the service run (a) on myrna or (b) on every DAQ hub (ignatius, zeppelin).
  - on myrna the snapshot service would query the database on the same machine, then send the snapshot to ignatius (either direct to mdreceiver as a large payload or by saving to a net-mounted drive); the advantage is minimizing redundant services, the disadvantage is it requires daq service to tell the snapshot service both to collect the snapshot and where to send it on to
  - on ignatius, the snapshot would query the database on myrna and then save locally; the disadvantages are more machines with dragonfly and redundant services, the advantage is that the large data query is by sql, not dripline
2. Motivation for handling the snapshot as an alert (in either above scenario) is that the DAQ doesn't need to wait for the query.  In the event of failure, the query can always be redone by hand since the data still exists in the db.
3. DAQ service is currently written to provide one metadata and one snapshot file, hornet expects a separate pre- and post- snapshot.  Which is preferred?
4. Currently the LOGS and LATEST snapshots have different data saved.  One has value_cal and one has both raw and cal; one has only specified endpoints and the other has all.
5. Since the SQL snapshot is theoretically completely replicable, that would require the stop timestamp to exist in a database.  The start_time is received from the run db, but this db contains neither the run_time nor the stop_time.  Additionally, is it worth saving a more precise run start/stop to clean out some of the overhead (e.g., for the RSA, start is redefined (or true_start is defined) as the time right before telling the rsa_service to start the run, and stop is defined as the time right after stopping, instead of start being defined by a db query and then we do a bunch of gets and configure the instrument, etc).

**Comment by guiguem** [comment]
![img_0817](https://cloud.githubusercontent.com/assets/16764756/20771758/9dc4dfd8-b6ff-11e6-973e-004bc80f5bd4.JPG)

**Comment by les67** [comment]
A few more questions to start off:

1. Will the list of endpoints to query the db be now specified in the snapshot service config instead of the daq config?
2. The daq service will send the snapshot service a request at the end of a run with the following information about the completed run: start timestamp, end timestamp, directory path for file allocation. For the start timestamp I will use the start_timestamp value from the db which is created when the run id is assigned. For the end timestamp I plan to keep using datetime.utcnow() at whatever time the end_run method is called in DAQProvider. Is this suitable for now?
3. Since the snapshot will be taken as a request from the daq service, what should it return? are return None or 0 good enough, or more specific?
4. The final file to be written is requested to be one json dictionary with a key for each endpoint in the provided query list. If we want to put together both get_latest and get_logs outputs per endpoint, one entry in the snapshot dictionary will look like this:
```
		"flux_capacitance": [
			{
				"timestamp": "2016-11-15T22:15:00Z",
				"value_cal": 1.5
			},
			{
				"timestamp": "2016-11-15T22:14:30Z",
				"value_cal": 1.5
			},
			{
				"timestamp": "2016-11-15T22:13:59Z",
				"value_cal": 1.5
			},
			{
				"timestamp": "2016-11-15T22:13:28Z",
				"value_cal": 1.5
			},
			{
				"timestamp": "2016-11-15T22:12:58Z",
				"value_cal": 1.5
			}
		],
```
where the last sub-entry is the result of get_latest and the rest are the result of get_logs. Is this how we want this to be structured?

**Comment by wcpettus** [comment]
1. That is best.  This way we define the endpoints once in the snapshot service and don't need to define separately the endpoints in the RSA and psyllid config files (and make sure they match).
2. Sounds good
3. Sounds good
4. Sounds good, that makes everything time-ordered

**Comment by guiguem** [comment]
1. Great!
2. Great!
3. Or maybe a sentence like "everything went fine"
4. Great!

**Comment by les67** [comment]
Taken care of with pull request #81.
