### ISSUE TITLE
Secondary data flow tree structure

### ISSUE THREAD

**Issue by guiguem** [project8/dragonfly#94]
We want a new tree structure for the calibration data based on the time, in order to reduce the number of files per folder below 1000.
The proposed scheme is
```/base_path/<type>/<raw/proc>/<yyyy>/<mm>/<dd>/<yyyymmdd_hhmmss>/<data>```
with ```<type>``` being ```esr``` or ```rf_bkgd```
```<base_path>``` is ```/data/secondary``` on claude and ```S:\\``` for the RSA.
We have to do that for:
- [x] ESR
- [x] RSAAcquisitionInterface: save_trace

**Comment by wcpettus** [comment]
Some minor quibbles:
- Is there a reason to do `<mm>/<dd>` instead of just `<mmdd>`?  The latter removes one recursion level and can never exceed 366.
- We've never come close to running 1000 RF bkgd scans in a month, so that could also be reduced to `<mm>` (instead of `<mmdd>`), although this makes an assumption that we won't drastically change our procedure in the future.
- Based on the ESR runs that I've already taken, the most convenient scheme would be to have a default of `<mmdd>` but with an option to provide an alternate key.  Commissioning datasets frequently spanned multiple day(s) but with a common theme while staying <<1000 runs.  It should be simple to ensure that it still starts with a datestamp (e.g., `<mmdd_key>`) so that lists are ordered correctly.

**Comment by guiguem** [comment]
Whatever the scheme is, it should be the same for both ESR and RF backgrounds.
The problem with options is that it also requires flexibility on the dirac side, which is out of "our" hands... so this is why I am not in favor of this "key".

**Comment by wcpettus** [comment]
Dirac doesn't just take the directory structure we give it?

**Comment by guiguem** [comment]
yes if does but then the analysis on the cluster will require us to give the mmdd and the possibility of the key, which will add complexity where I don't see the need.

**Comment by wcpettus** [comment]
solved in v1.5.4
