### ISSUE TITLE
repeater between two brokers

### ISSUE THREAD

**Issue by guiguem** [project8/dragonfly#97]
Need to be able to send messages between two different brokers/AMQP zones.
We should be able to select to have one or two direction repetition and select the type of message to be repeated or reject (through routine key pattern selection)

**Comment by laroque** [comment]
Some design/feature comments:

- a bi-directional repeater is difficult. Instead, each repeater should be a "service" for one dripline mesh and a "pure client" in the other. If you want bi-directional communication then each mesh would have a service providing access to the other. This also makes the logic much easier, since you probably don't want symmetric access between the systems.
- Access restrictions would then be achieved, similar to with the existing repeaters used for prologix boxes, by what endpoints exist in the repeater service. For example the provider itself would implement `set_condition` such that it passes any received `set_condition` to the target mesh. Then a general error which triggers set_condition 10 in the T2 zone ("broadcast.set_condition 10") would hit both systems, or you could address the repeater directly and condition 10 would be set only in the p8 zone (say because of an RGA scan). You could similarly add endpoints that send particular requests, serving basically as virtual targets for the resources on the other side.

**Comment by laroque** [comment]
I'm going to start working on this on the feature/dripline-repeater branch, may not have time to get very far tonight.

**Comment by laroque** [comment]
Implemented, tested with two independent docker-compose projects successfully.

The config file for the repeater service looks like:
```yaml
name: t2_repeater_service
module: Spimescape
broker: t2_broker
endpoints:
  - name: t2_to_insectarium_portal
    module: MeshRepeater
    target_broker: rabbit_broker
    endpoints:
      - name: insert_valve
        module: ProxyEndpoint
        target: insert_valve
```

The structure is that MeshRepeater is a *pure dripline client* on the dripline mesh with broker hosted on `target_broker`, and this config is run as a normal service on the mesh with broker hosted on `broker` in the `Spimescape` config.
- Note that we are moving away from specifying the broker for a service in the config file but I put it here because that is not done yet and it is more clear for explaining this example.
- Further note that MeshRepeater requires that the target broker be specified in the config file, but uses the username and password from the authentication file. This makes sense because the broker is clearly non-standard here, but there's nothing to prevent us from adding the t2-side host user/password to the lab-side broker's available users.

Every `ProxyEndpoint` added to the configuration is an exact link to its configured target, the target is effectively and available target on each mesh. That is to say, the ProxyEndpoint binds to `self.name.#` on the local mesh, and forwards all requests to `self._target.#` (where any provided RKS is preserved in the process). This link is one directional, the only messages from the target mesh that get back to the main mesh are ReplyMessages in response to a RequestMessage.

This feature is merged into develop.
